version: '3.7'
services:
  mongodb-primary:
    container_name: mongoDBNevook
    image: docker.io/bitnami/mongodb:4.4-debian-10
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=pNevook
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=Nevook
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodb_data_container:/bitnami/mongodb
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    ports:
      - 8091:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDBNevook
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - mongodb-primary
    links:
      - mongodb-primary
    networks:
      - mongo-compose-network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1080:8025
      - 1025:1025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
  # pushgateway:
  #   image: prom/pushgateway:v0.4.0
  #   ports:
  #     - 9091:9091

  redis:
    container_name: dev_redis
    image: redis
    ports:
      - 6379:6379

  redis-commander:
    container_name: dev_redis_commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8093:8081'

  rabbitmq:
    container_name: dev_rabbitmq
    image: rabbitmq:3.8.11-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  maildir: {}
  mongodb_data_container:
    driver: local

networks:
  mongo-compose-network:
    driver: bridge
